using System;
using System.CodeDom.Compiler;
using IncrementialMapper.Syntax.Tokens;
using IncrementialMapper.SyntaxProviders.Enums;
using Microsoft.CodeAnalysis;

namespace IncrementialMapper.SyntaxProviders;

internal static class SourceGenerator
{
    public static void GenerateCode(ClassToken token, SourceProductionContext context)
    {
        IndentedTextWriter writer = token.Writer;
        
        // Generate the auto generated comment, and namespace.
        writer
            .AppendAutoGeneratedComment()
            .Append("#nullable enable").AppendLine().AppendLine()
            .AppendNamespace(token).AppendLine();

        token.CreateSourceClass();

        // Close the namespace again.
        writer.AppendFormat(FormatType.ClosedCurlyBraces, IndentType.Outdent);

        string finalText = writer.InnerWriter.ToString();

        context.AddSource($"MapperFrom{token.SourceClass.Name}To{token.TargetClass.Name}.g.cs", writer.InnerWriter.ToString());
    }
}