using System.CodeDom.Compiler;
using IncrementialMapper.Internal.Syntax.Providers.Enums;

namespace IncrementialMapper.Internal.Syntax.Providers;

internal static class FormatProvider
{
    private const string AUTO_GENERATED_COMMENT = "/// <auto-generated />";

    /// <summary>
    /// Appends either <c>(</c>, <c>)</c>, <c>{</c>, <c>}</c> into the TextWriter.
    /// </summary>
    public static IndentedTextWriter AppendFormat(this IndentedTextWriter writer, FormatType formatType, IndentType indentationType)
    {
        if (indentationType is IndentType.Outdent)
            writer.Indent--;
        
        if (formatType is not FormatType.None)
            writer.Write((char)formatType);
        
        if (indentationType is IndentType.Indent)
            writer.Indent++;
        
        return writer;
    }
    
    public static IndentedTextWriter AppendAutoGeneratedComment(this IndentedTextWriter writer)
    {
        return writer
                .Append(AUTO_GENERATED_COMMENT)
                .AppendNewLine();
    }
    
    public static IndentedTextWriter AppendNewLine(this IndentedTextWriter writer, int newlineCount = 1)
    {
        for(var i = 0; i < newlineCount; i++)
            writer.WriteLine();
        
        return writer;
    }

    public static IndentedTextWriter Append(this IndentedTextWriter writer, string text)
    {
        writer.Write(text);
        return writer;
    }
}
