using System.CodeDom.Compiler;
using System.Collections.Generic;
using IncrementialMapper.Internal.Syntax.Providers.Enums;
using IncrementialMapper.Internal.Syntax.Tokens;
using Microsoft.CodeAnalysis;

namespace IncrementialMapper.Internal.Syntax.Providers;

internal static class SourceGenerator
{
    public static void GenerateCode(ClassToken token, SourceProductionContext context)
    {
        IndentedTextWriter writer = token.Writer;

        // Generate the auto generated comment, and namespace.
        writer
            .AppendAutoGeneratedComment()
            .Append("#nullable enable").AppendNewLine()
            .AppendNamespaces(token.NameSpaces).AppendNewLine(2)
            .Append($"namespace {token.Namespace}").AppendNewLine()
            .AppendFormat(FormatType.OpenCurlyBraces, IndentType.Indent).AppendNewLine();

        token.GenerateSourceClass();

        // Close the namespace again.
        writer.AppendFormat(FormatType.ClosedCurlyBraces, IndentType.Outdent);

        context.AddSource($"MapperFrom{token.SourceClass.Name}To{token.TargetClass.Name}.g.cs", writer.InnerWriter.ToString());
    }

    private static IndentedTextWriter AppendNamespaces(this IndentedTextWriter writer, HashSet<string> usingNamespaces)
    {
        foreach (string namespaceName in usingNamespaces)
            writer.Append($"using {namespaceName};");

        return writer;
    }
}